/*
 * generated by Xtext
 */
package uk.ac.kcl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uk.ac.kcl.ui.internal.MDEOptimiseActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MDEOptimiseExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MDEOptimiseActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MDEOptimiseActivator.getInstance().getInjector(MDEOptimiseActivator.UK_AC_KCL_MDEOPTIMISE);
	}
	
}
