/*
 * generated by Xtext
 */
package uk.ac.kcl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MDEOptimiseUiModule extends uk.ac.kcl.ui.AbstractMDEOptimiseUiModule {
	public MDEOptimiseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
