/*
 * generated by Xtext
 */
package uk.ac.kcl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MDEOptimiseUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return uk.ac.kcl.ui.internal.MDEOptimiseActivator.getInstance().getInjector("uk.ac.kcl.MDEOptimise");
	}
	
}
