/**
 * generated by Xtext
 */
package uk.ac.kcl.ui.contentassist;

import uk.ac.kcl.ui.contentassist.AbstractMDEOptimiseProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MDEOptimiseProposalProvider extends AbstractMDEOptimiseProposalProvider {
}
