/*
 * generated by Xtext
 */
package uk.ac.kcl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MDEOptimiseGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class OptimisationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Optimisation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBasepathAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cBasepathBasepathSpecParserRuleCall_0_0 = (RuleCall)cBasepathAssignment_0.eContents().get(0);
		private final Assignment cMetamodelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMetamodelMetaModelSpecParserRuleCall_1_0 = (RuleCall)cMetamodelAssignment_1.eContents().get(0);
		private final Assignment cFitnessAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFitnessFitnessFunctionSpecParserRuleCall_2_0 = (RuleCall)cFitnessAssignment_2.eContents().get(0);
		private final Assignment cEvolversAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEvolversEvolverSpecParserRuleCall_3_0 = (RuleCall)cEvolversAssignment_3.eContents().get(0);
		
		//Optimisation:
		//	basepath=BasepathSpec metamodel=MetaModelSpec fitness=FitnessFunctionSpec evolvers+=EvolverSpec+;
		@Override public ParserRule getRule() { return rule; }

		//basepath=BasepathSpec metamodel=MetaModelSpec fitness=FitnessFunctionSpec evolvers+=EvolverSpec+
		public Group getGroup() { return cGroup; }

		//basepath=BasepathSpec
		public Assignment getBasepathAssignment_0() { return cBasepathAssignment_0; }

		//BasepathSpec
		public RuleCall getBasepathBasepathSpecParserRuleCall_0_0() { return cBasepathBasepathSpecParserRuleCall_0_0; }

		//metamodel=MetaModelSpec
		public Assignment getMetamodelAssignment_1() { return cMetamodelAssignment_1; }

		//MetaModelSpec
		public RuleCall getMetamodelMetaModelSpecParserRuleCall_1_0() { return cMetamodelMetaModelSpecParserRuleCall_1_0; }

		//fitness=FitnessFunctionSpec
		public Assignment getFitnessAssignment_2() { return cFitnessAssignment_2; }

		//FitnessFunctionSpec
		public RuleCall getFitnessFitnessFunctionSpecParserRuleCall_2_0() { return cFitnessFitnessFunctionSpecParserRuleCall_2_0; }

		//evolvers+=EvolverSpec+
		public Assignment getEvolversAssignment_3() { return cEvolversAssignment_3; }

		//EvolverSpec
		public RuleCall getEvolversEvolverSpecParserRuleCall_3_0() { return cEvolversEvolverSpecParserRuleCall_3_0; }
	}

	public class BasepathSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BasepathSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBasepathKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLocationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLocationURLTerminalRuleCall_1_0 = (RuleCall)cLocationAssignment_1.eContents().get(0);
		
		/// **
		// * Use this to identify a basepath to be set in the HenshinResourceSet so that Henshin 
		// * transformations referencing file-based meta-models through relative paths will work 
		// * correctly. This will happen mainly when working with dynamic instances rather than 
		// * fully generated and registered metamodels. All further URLs should be either absolute 
		// * or relative to this basepath.
		// * / BasepathSpec:
		//	"basepath" location=URL;
		@Override public ParserRule getRule() { return rule; }

		//"basepath" location=URL
		public Group getGroup() { return cGroup; }

		//"basepath"
		public Keyword getBasepathKeyword_0() { return cBasepathKeyword_0; }

		//location=URL
		public Assignment getLocationAssignment_1() { return cLocationAssignment_1; }

		//URL
		public RuleCall getLocationURLTerminalRuleCall_1_0() { return cLocationURLTerminalRuleCall_1_0; }
	}

	public class MetaModelSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MetaModelSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMetamodelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLocationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLocationURLTerminalRuleCall_1_0 = (RuleCall)cLocationAssignment_1.eContents().get(0);
		
		//MetaModelSpec:
		//	"metamodel" location=URL;
		@Override public ParserRule getRule() { return rule; }

		//"metamodel" location=URL
		public Group getGroup() { return cGroup; }

		//"metamodel"
		public Keyword getMetamodelKeyword_0() { return cMetamodelKeyword_0; }

		//location=URL
		public Assignment getLocationAssignment_1() { return cLocationAssignment_1; }

		//URL
		public RuleCall getLocationURLTerminalRuleCall_1_0() { return cLocationURLTerminalRuleCall_1_0; }
	}

	public class FitnessFunctionSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FitnessFunctionSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFitnessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cClassAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cClassSTRINGTerminalRuleCall_1_0 = (RuleCall)cClassAssignment_1.eContents().get(0);
		
		//FitnessFunctionSpec:
		//	"fitness" class=STRING;
		@Override public ParserRule getRule() { return rule; }

		//"fitness" class=STRING
		public Group getGroup() { return cGroup; }

		//"fitness"
		public Keyword getFitnessKeyword_0() { return cFitnessKeyword_0; }

		//class=STRING
		public Assignment getClassAssignment_1() { return cClassAssignment_1; }

		//STRING
		public RuleCall getClassSTRINGTerminalRuleCall_1_0() { return cClassSTRINGTerminalRuleCall_1_0; }
	}

	public class EvolverSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EvolverSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEvolveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cUsingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cRule_locationAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRule_locationURLTerminalRuleCall_2_0 = (RuleCall)cRule_locationAssignment_2.eContents().get(0);
		private final Keyword cUnitKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUnitAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUnitSTRINGTerminalRuleCall_4_0 = (RuleCall)cUnitAssignment_4.eContents().get(0);
		
		//EvolverSpec: // This expects to be passed in a Henshin model
		//// TODO We may also want to allow the specification of parameters, but not for now. 
		//	"evolve" "using" rule_location=URL "unit" unit=STRING;
		@Override public ParserRule getRule() { return rule; }

		//// This expects to be passed in a Henshin model
		//// TODO We may also want to allow the specification of parameters, but not for now. 
		//"evolve" "using" rule_location=URL "unit" unit=STRING
		public Group getGroup() { return cGroup; }

		//// This expects to be passed in a Henshin model
		//// TODO We may also want to allow the specification of parameters, but not for now. 
		//"evolve"
		public Keyword getEvolveKeyword_0() { return cEvolveKeyword_0; }

		//"using"
		public Keyword getUsingKeyword_1() { return cUsingKeyword_1; }

		//rule_location=URL
		public Assignment getRule_locationAssignment_2() { return cRule_locationAssignment_2; }

		//URL
		public RuleCall getRule_locationURLTerminalRuleCall_2_0() { return cRule_locationURLTerminalRuleCall_2_0; }

		//"unit"
		public Keyword getUnitKeyword_3() { return cUnitKeyword_3; }

		//unit=STRING
		public Assignment getUnitAssignment_4() { return cUnitAssignment_4; }

		//STRING
		public RuleCall getUnitSTRINGTerminalRuleCall_4_0() { return cUnitSTRINGTerminalRuleCall_4_0; }
	}
	
	
	private final OptimisationElements pOptimisation;
	private final BasepathSpecElements pBasepathSpec;
	private final MetaModelSpecElements pMetaModelSpec;
	private final FitnessFunctionSpecElements pFitnessFunctionSpec;
	private final EvolverSpecElements pEvolverSpec;
	private final TerminalRule tURL;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MDEOptimiseGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pOptimisation = new OptimisationElements();
		this.pBasepathSpec = new BasepathSpecElements();
		this.pMetaModelSpec = new MetaModelSpecElements();
		this.pFitnessFunctionSpec = new FitnessFunctionSpecElements();
		this.pEvolverSpec = new EvolverSpecElements();
		this.tURL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "URL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uk.ac.kcl.MDEOptimise".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Optimisation:
	//	basepath=BasepathSpec metamodel=MetaModelSpec fitness=FitnessFunctionSpec evolvers+=EvolverSpec+;
	public OptimisationElements getOptimisationAccess() {
		return pOptimisation;
	}
	
	public ParserRule getOptimisationRule() {
		return getOptimisationAccess().getRule();
	}

	/// **
	// * Use this to identify a basepath to be set in the HenshinResourceSet so that Henshin 
	// * transformations referencing file-based meta-models through relative paths will work 
	// * correctly. This will happen mainly when working with dynamic instances rather than 
	// * fully generated and registered metamodels. All further URLs should be either absolute 
	// * or relative to this basepath.
	// * / BasepathSpec:
	//	"basepath" location=URL;
	public BasepathSpecElements getBasepathSpecAccess() {
		return pBasepathSpec;
	}
	
	public ParserRule getBasepathSpecRule() {
		return getBasepathSpecAccess().getRule();
	}

	//MetaModelSpec:
	//	"metamodel" location=URL;
	public MetaModelSpecElements getMetaModelSpecAccess() {
		return pMetaModelSpec;
	}
	
	public ParserRule getMetaModelSpecRule() {
		return getMetaModelSpecAccess().getRule();
	}

	//FitnessFunctionSpec:
	//	"fitness" class=STRING;
	public FitnessFunctionSpecElements getFitnessFunctionSpecAccess() {
		return pFitnessFunctionSpec;
	}
	
	public ParserRule getFitnessFunctionSpecRule() {
		return getFitnessFunctionSpecAccess().getRule();
	}

	//EvolverSpec: // This expects to be passed in a Henshin model
	//// TODO We may also want to allow the specification of parameters, but not for now. 
	//	"evolve" "using" rule_location=URL "unit" unit=STRING;
	public EvolverSpecElements getEvolverSpecAccess() {
		return pEvolverSpec;
	}
	
	public ParserRule getEvolverSpecRule() {
		return getEvolverSpecAccess().getRule();
	}

	//terminal URL: // TODO: We can probably provide a more fine-grained specification here
	//	"<" !">"* ">";
	public TerminalRule getURLRule() {
		return tURL;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
