/**
 * generated by Xtext
 */
package uk.ac.kcl.validation;

import uk.ac.kcl.validation.AbstractMDEOptimiseValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MDEOptimiseValidator extends AbstractMDEOptimiseValidator {
}
