/*
 * generated by Xtext
 */
package uk.ac.kcl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MDEOptimiseRuntimeModule extends uk.ac.kcl.AbstractMDEOptimiseRuntimeModule {

}
