/*
 * generated by Xtext
 */
package uk.ac.kcl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MDEOptimiseStandaloneSetup extends MDEOptimiseStandaloneSetupGenerated{

	public static void doSetup() {
		new MDEOptimiseStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

